server:
  port: 8989

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://0/0?useSSL=false&allowMultiQueries=true
    #username: root
    username: 0
    password: 0


  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
mybatis-plus:
  #configuration:
  # 日志
  #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
#oss:
#  accessKey: 0
#  secretKey: 0
#  bucket: 0

  # 配置redis
#redis:
#  host: 0
#  port: 6379
#  password: 0
#  lettuce:
#    pool:
#      max-active: 8   #最大连接数
#      max-idle: 8     #最大空闲连接数
#      min-idle: 0     #最小空闲连接数
#      max-wait: 100ms #等待连接时间

oss:
  endpoint: 0
  keyid: 0
  keysecret: 0
  bucketname: 0
