server:
  port: 8989

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.109.90.13:3306/zy_blog?useSSL=false&allowMultiQueries=true
    #username: root
    username: zy_blog
    password: 120125hzy.


  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
mybatis-plus:
  #configuration:
  # 日志
  #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
#oss:
#  accessKey: LrnU-gOYl3G7PMpJTnI4eZyUcQKz6ID3rJeKjKrb
#  secretKey: NexKDL8mHzWiP5OdoDXzfQ5AqSRiX_VpTFQ-lXlp
#  bucket: qaq-blog

  # 配置redis
#redis:
#  host: 47.109.90.13
#  port: 6379
#  password: 120125hzy.
#  lettuce:
#    pool:
#      max-active: 8   #最大连接数
#      max-idle: 8     #最大空闲连接数
#      min-idle: 0     #最小空闲连接数
#      max-wait: 100ms #等待连接时间

oss:
  endpoint: oss-cn-chengdu.aliyuncs.com
  keyid: LTAI5tDwkMpEN267sGWBDB2q
  keysecret: sIVcsIMjXc4rZoDwjhxU5mFs4QDgz9
  bucketname: zyqaq-blog